config/routes.rb
Eventum::Application.routes.draw do
  
  get 'cities/update_states', as: :update_states
  get 'cities/update_cities', as: :update_cities
  resources :events do
    member do
      post 'follow'
      post 'unfollow'
    end
  end

  devise_for :users, controllers: {registrations: 'users/registrations'}
  resources :categories

  resources :cities

  resources :states

  resources :countries

  get '/eventos-en/:city' => 'site#index', as: :root_with_city
  get '/eventos-de/:category' => 'site#index', as: :root_with_category
  root :to => 'site#index'

  post 'cities_by_state' => 'events#cities_by_state'

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  date_start  :datetime
#  date_end    :datetime
#  category_id :integer
#  city_id     :integer
#  location    :string(255)
#  user_id     :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Event < ActiveRecord::Base
  belongs_to :category
  belongs_to :city
  belongs_to :user
  has_and_belongs_to_many :followers, class_name: 'User'

  resourcify

  mount_uploader :image, ImageUploader

  def date
    if date_start.yday == date_end.yday && date_start.year == date_end.year
      "#{I18n.localize(date_start)} - #{date_end.hour}:#{date_end.min.to_s.rjust(2, '0')}"
    else
      "#{I18n.localize(date_start)} - #{I18n.localize(date_end)}"
    end
  end

  def city_state
    "#{city.name}, #{city.state.name}" unless city.nil? or city.state.nil?
  end

  def is_followed_by(user)
    followers.exists? (user.id)
  end

  def self.recents(count)
    Event.order(:date_start).limit(count)
  end

  def self.recents_from_city(city_name)
    Event.joins(:city).where(cities: {name: city_name})
  end

  def self.recents_of_category(category_name)
    Event.joins(:category).where(categories: {name: category_name})
  end

  def self.not_followed_by(user)
    @event_ids = Event.includes(:followers).where("events_users.user_id = #{user.id}").select(:id)
    if @event_ids.count == 0
      @event_ids = 0
    end

    Event.includes(:followers)
      .where("(events_users.user_id <> #{user.id} or events_users.user_id is null)")
      .where("(events_users.event_id not in (?)) or events_users.user_id is null", @event_ids)
      .references('events_users')
  end

  def self.coming(count=5)
  	Event.where('date_start > ?', Time.now).order(:date_start).limit(count)
  end

  def self.published_by(user)
    Event.where(user: user)
  end

  def self.followed_by(user)
    user.events
  end

  def self.events_in_city_of(user, count = 5)
    Event.not_followed_by(user).where(city_id: user.city.id).order(:date_start).limit(count)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :follow, :unfollow]
  before_action :fill_tables, only: [:new, :create, :edit, :update]
  before_action :authenticate_user!, except: [:show]

  # GET /events
  # GET /events.json
  def index
    if current_user.has_role? :publisher
      @events = Event.published_by current_user
      index_publisher
    elsif current_user.has_role? :member
      @events = Event.followed_by current_user
      @events_in_city = Event.events_in_city_of current_user
      index_member
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    date_start = Time.zone.parse(event_params[:date_start])
    date_end = Time.zone.parse(event_params[:date_end])

    @event.date_start = date_start
    @event.date_end = date_end
    if params[:city_id].nil? then
      @event.city = current_user.city
    else
      @event.city = City.find(params[:city_id])
    end
    @event.user = current_user

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  def follow
    if not @event.is_followed_by(current_user)
      @event.followers << current_user
      respond_to do |format|
        format.json { head :no_content }
      end
    end
  end

  def unfollow
    if @event.is_followed_by(current_user)
      @event.followers.delete(current_user)
      respond_to do |format|
        format.json { head :no_content }
      end
    end
  end

  protected
  def index_publisher
    render(template: 'events/index_publisher')
  end

  def index_member
    render(template: 'events/index_member')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    def fill_tables
      @categories = Category.all
      @countries = Country.all
      @states = State.none
      @cities = City.none
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :date_start, :date_end, :category_id, :city_id, :location, :user_id, :image)
    end
end

app/helpers/events_helper.rb
module EventsHelper

  def link_to_follow(event)

    html = ''

    if event.is_followed_by(current_user)
      html << link_to('Seguir', follow_event_path(event), method: :post, id: 'lnkFollowEvent', class: 'hidden-link')
      html << link_to('Dejar de seguir', unfollow_event_path(event), method: :post, id: 'lnkUnfollowEvent', class: 'visible-link')
    else
      html << link_to('Seguir', follow_event_path(event), method: :post, id: 'lnkFollowEvent', class: 'visible-link')
      html << link_to('Dejar de seguir', unfollow_event_path(event), method: :post, id: 'lnkUnfollowEvent', class: 'hidden-link')
    end
    return raw(html)
  end

end

app/views/events/_details.html.erb
<div class="event">
  <h5><%= link_to event.name, event_path(event) %></h5>
  <span class="date_start"><%= l event.date_start %></span><br/>
  <span class="date_end"><%= l event.date_end %></span><br/>
  <span class="category"><%= event.category.name unless event.category.nil? %></span><br/>
  <span class="location"><%= event.location %></span><br/>
</div>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
<% if @event.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@event.errors.count, 'error') %> prohibited this event from being saved:</h2>

  <ul>
    <% @event.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :description %>
  <%= f.text_area :description %>
</div>
<div class="field">
  <%= f.label :date_start %>
  <% if f.object.date_start.nil? then %>
  <%= f.text_field :date_start %>
  <% else %>
  <%= f.text_field :date_start, value: l(f.object.date_start) %>
  <% end %>
</div>
<div class="field">
  <%= f.label :date_end %>
  <% if f.object.date_end.nil? then %>
  <%= f.text_field :date_end %>
  <% else %>
  <%= f.text_field :date_end, value: l(f.object.date_end) %>
  <% end %>
</div>
<div class="field">
  <%= f.label :category_id %>
  <%= f.collection_select :category_id, @categories, :id, :name, {prompt: ' - '} %>
</div>

<div class="field">
  Ciudad del evento: <%= my_city(current_user) %><br/>
  <%= link_to 'Cambiar ciudad', root_path %>
</div>

<div class="field">
  <%= f.label :location %>
  <%= f.text_field :location %>
</div>

<div class="field">
  <%= f.file_field :image %>
  <img id='imagePreview' src='#' alt='Event image' />
</div>

<div class="actions">
  <%= f.submit %>
</div>
<% end %>

<script>

$(document).ready(function () {

  $('#event_date_start').datetimepicker({
    dateFormat: "dd/mm/yy",
    timeFormat: "HH:mm",
    onClose: function() {
      var date_end = $('#event_date_end').val();
      if(date_end.length != 0) {
        return;
      }

      var date_start = $('#event_date_start').val();
      $('#event_date_end').val(date_start);
    }
  });
  $('#event_date_end').datetimepicker({
    dateFormat: "dd/mm/yy",
    timeFormat: "HH:mm"
  });

  $('#country_select').change(function () {
    $.ajax({
      url: "<%= update_states_path %>",
      data: {
        country_id: $('#country_select').val()
      },
      dataType: 'script'
    });
    $('#state_select').removeAttr('disabled');
  });
  $('#state_select').change(function () {
    $.ajax({
      url: "<%= update_cities_path %>",
      data: {
        state_id: $('#state_select').val()
      },
      dataType: 'script'
    });
    $('#city_select').removeAttr('disabled');
  });

  $('#event_image').change(function(event) {
    var files = $('#event_image').prop('files');

    if (files && files[0]) {
      var reader = new FileReader();

      reader.onload = function (e) {
        $('#imagePreview').attr('src', e.target.result).width(150).height(200);
      };

      reader.readAsDataURL(files[0]);
    };
  });

});
</script>

app/views/events/_select_city.html.erb
<div class="field">
  <%= f.label :country_select %>
  <%= collection_select nil, :country_id, @countries, :id, :name,
                        {prompt: ' - '}, {id: 'country_select', name: 'country_id'} %>
</div>
<div class="field">
  <%= f.label :state_select %>
  <%= collection_select nil, :state_id, @states, :id, :name,
                        {prompt: ' - '}, {id: 'state_select', name: 'state_id', disabled: 'disabled'} %>
</div>
<div class="field">
  <%= f.label :city_select %>
  <%= collection_select nil, :city_id, @cities, :id, :name,
                        {prompt: ' - '}, {id: 'city_select', name: 'city_id', disabled: 'disabled'} %>
</div>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Date</th>
    <th>Category</th>
    <th>City</th>
    <th>Location</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.description %></td>
        <td><%= event.date %></td>
        <td><%= event.category %></td>
        <td><%= event.city %></td>
        <td><%= event.location %></td>
        <td><%= event.user %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/index_member.html.erb
<h1>Mis eventos</h1>

<% if @events.count > 0 %>
    <ul class="list-events">
      <% @events.each do |event| %>

      <li>
        <%= link_to event.name, event_path(event) %>
      </li>

      <% end %>
    </ul>
<% else %>

    <h4>No estás siguiendo ningún evento</h4>

<% end %>

<h3>Eventos que te podrían interesar</h3>

<h5>Eventos en <%= current_user.city.name unless current_user.city.nil? %></h5>
<ul>
  <% @events_in_city.each do |event| %>

  <li>
  <%= link_to event.name, event_path(event) %>
    <%= event.date %>
  </li>

  <% end %>
</ul>

app/views/events/index_publisher.html.erb
<h1>Mis eventos</h1>

<% if @events.count > 0 %>

  <ul class='events-list'>
    <% @events.each do |event| %>

    <li>
      <div class='event container'>
        <div class='row'>

          <div class='span2 image'>
            <%= image_tag(event.image_url(:thumb), width: 100) if event.image? %>
          </div>
          <div class='span10'>
            <p class='title'>
              <%= link_to event.name, event %>
            </p>
            <p>
              <%= event.category.name unless event.category.nil? %>
            </p>
            <p>
              <%= event.date %>
            </p>
            <p>
              <%= event.location %>, <%= event.city_state %>
            </p>
          </div>
        </div>
        <div class="row">
          <div class="span12 actions">
            <div class="pull-right">
              <%= link_to 'Editar', edit_event_path(event) %>
              <%= button_to 'Eliminar', event, method: :delete, confirm: 'Seguro que desea eliminar el evento?' %>
            </div>
          </div>
        </div>
      </div>
    </li>

    <% end %>
  </ul>

<% else %>

    <h4>No has publicado ningún evento</h4>
    <%= link_to 'Publicar uno', new_event_path %>

<% end %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre del evento:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Inicio:</strong>
  <%= l @event.date_start %>
</p>

<p>
  <strong>Final:</strong>
  <%= l @event.date_end %>
</p>

<p>
  <strong>Categoría:</strong>
  <%= @event.category.name unless @event.category.nil? %>
</p>

<p>
  <strong>Ciudad:</strong>
  <%= @event.city.name unless @event.city.nil? %>, <%= @event.city.state.name unless @event.city.state.nil? %>
</p>

<p>
  <strong>Ubicación:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Usuario que publicó:</strong>
  <%= @event.user.username unless @event.user.nil? %>
</p>

<p>
  <%= image_tag @event.image_url(:thumb) if @event.image? %>
</p>

<% if can? :update, @event %>
  <%= link_to 'Editar', edit_event_path(@event) %> |
<% end %>
<% if can? :follow, @event %>
  <%= link_to_follow(@event) %>
<% end %>
<% if current_user %>
  <%= link_to 'Ver mis eventos', events_path %> |
<% end %>
<%= link_to 'Regresar', root_path %>