config/routes.rb
Eventum::Application.routes.draw do
  
  get 'cities/update_states', as: :update_states
  get 'cities/update_cities', as: :update_cities
  resources :events do
    member do
      post 'follow'
      post 'unfollow'
    end
  end

  devise_for :users, controllers: {registrations: 'users/registrations'}
  resources :categories

  resources :cities

  resources :states

  resources :countries

  get '/eventos-en/:city' => 'site#index', as: :root_with_city
  get '/eventos-de/:category' => 'site#index', as: :root_with_category
  root :to => 'site#index'

  post 'cities_by_state' => 'events#cities_by_state'

end

app/models/city.rb
# == Schema Information
#
# Table name: cities
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  state_id   :integer
#  created_at :datetime
#  updated_at :datetime
#

class City < ActiveRecord::Base
  belongs_to :state
  has_many :events

  def self.with_recent_events(count=5)
    City.joins(:events).select('cities.name, count(city_id) as "event_count"').group('cities.name').order(' event_count desc')
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render action: 'show', status: :created, location: @city }
      else
        format.html { render action: 'new' }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url }
      format.json { head :no_content }
    end
  end

  def update_states
    country = Country.find(params[:country_id])
    @states = country.states.map { |s| [s.name, s.id] }.insert(0, 'Select a state')
  end

  def update_cities
    state = State.find(params[:state_id])
    @cities = state.cities.map { |c| [c.name, c.id] }.insert(0, 'Select a city')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name, :state_id)
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_form.html.erb
<%= form_for(@city) do |f| %>
  <% if @city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% @city.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing city</h1>

<%= render 'form' %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<h1>Listing cities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>State</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= city.name %></td>
        <td><%= city.state %></td>
        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_city_path %>

app/views/cities/new.html.erb
<h1>New city</h1>

<%= render 'form' %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @city.name %>
</p>

<p>
  <strong>State:</strong>
  <%= @city.state %>
</p>

<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>

app/views/cities/update_cities.js.erb
$('#city_select').html("<%= escape_javascript(options_for_select(@cities)) %>");

app/views/cities/update_states.js.erb
$('#state_select').html("<%= escape_javascript(options_for_select(@states)) %>");